included:
  - grift
  - griftTests
  - GriftKit
  - GriftKitTests
excluded:
  - GriftKit/TestFile.swift
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
disabled_rules:
  - force_cast
  - force_try
  - todo
  - variable_name

line_length: 160
